### ISSUE TITLE
Xenserver on NixOS

### ISSUE THREAD

**Issue by ts468** [xenserver/buildroot#615]
Hi!

I'm currently working on integrating Xenserver into NixOS, and I wondered if you could maybe help me.
The whole xenserver toolstack already builds. For the moment I'm just not clear which version of xen to use, and which patches to apply. The options I'm considering are:
- xen-4.4.1 as released
- xen-4.4.1 + patches from xen-4.4-pq
- xen-4.5.0 as released
- xen-4.5.0 + patches from xen-4.5-pq
What is the correct version of xen to use for xenserver?

Also, what is ocaml-xen-lowlevel-libs for? Does that library work with xen-4.5 already?

Many thanks in advance!
Thomas

**Comment by djs55** [comment]
On Mon, Feb 2, 2015 at 1:33 PM, ts468 <notifications@github.com> wrote:

> Hi!
>
> I'm currently working on integrating Xenserver into NixOS, and I wondered
> if you could maybe help me.
> The whole xenserver toolstack already builds.
>
Great!

For the moment I'm just not clear which version of xen to use, and which
> patches to apply. The options I'm considering are:
>
>    - xen-4.4.1 as released
>    - xen-4.4.1 + patches from xen-4.4-pq
>    - xen-4.5.0 as released
>    - xen-4.5.0 + patches from xen-4.5-pq What is the correct version of
>    xen to use for xenserver?
>
>
That's a very good question. We're trying to keep the code flexible so that
it works with xen 4.4 and xen 4.5 to help people who want to be as close to
regular upstream Xen as possible. However the closer your Xen version is to
the one in xenserver the better it will work. Some features will rely on
the patches in the Xen patchequeue for sure. @euanh was investigating
getting the buildroot build to work with the current xenserver xen-4.5-pq
version on CentOS recently.

So I would recommend using xen-4.5.0 + patches from xen-4.5-pq if this is
possible.

>
>
> Also, what is ocaml-xen-lowlevel-libs for? Does that library work with
> xen-4.5 already?
>
Another good question :-) My goal with that repo was to have a more recent
version of the OCaml libxl, libxc stubs that were commonly available in
distros, for example to backport fixes from xen-4.5 to xen-4.4. Xenserver
doesn't use this repo. If you use the xen-4.5 from xenserver then you
probably don't need it either.

Cheers (and good luck!)
Dave

> Many thanks in advance!
> Thomas
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xenserver/buildroot/issues/615>.
>



-- 
Dave Scott

**Comment by ts468** [comment]
Thanks!

I've filed an issue at https://github.com/xapi-project/ocaml-xen-lowlevel-libs/issues/76.

About the xen-4.4-pq, I've also tried to patch Xen 4.4.0, which is the basis for Xen in http://xenbits.xen.org/djs/centos-xen-4-4/, but it doesn't fit either.

As I understand that XenServer 6.5 is based on Xen 4.4 I'm trying to get the hypervisor patched so that it matches the one from the XenServer 6.5 release.
Would xen-4.4.pq be the right patch queue for that?

**Comment by andyhhp** [comment]
Your build issue with ocaml-xen-lowlevel-libs is because ocaml-xen-lowlevel-libs has its own cached copy of the libxl IDL.  This is the reason I ripped it out of XenServer trunk in the first place.  The only viable soltuion is to delete all of that, including the now-wrong IDL->Ocaml conversion script.

What is wrong with building the stubdoms?  There is currently an outstanding issue against Xen 4.5 that stubdoms do not function, but they should build fine.

**Comment by ts468** [comment]
@andyhhp, thanks for help!

Concerning the stubdoms, I tried to capture the build failure of Xen 4.5 with xen-4.5.pq applied: https://gist.github.com/ts468/1f88f8c54b13d1bf26d3

About the ocaml-xen-lowlevel-libs, do I understand you correctly that the issue will be fixed upstream in https://github.com/xapi-project/ocaml-xen-lowlevel-libs?

**Comment by andyhhp** [comment]
Ah - this is all mixed up in the migration v2 code.  http://xenbits.xen.org/gitweb/?p=xen.git;a=commitdiff;h=755a7aaee0944800ff8666715ec32b88775816b2 is one I prepared earlier,  You will also need to edit https://github.com/xenserver/xen-4.5.pg/blob/master/master/0002-tools-libxc-Implement-writev_exact-in-the-same-style.patch to have "#ifndef __MINIOS__" blocked around all of the additions.

As for ocaml-xen-lowlevel-libs - you do not need them.  The reason I removed them from XenServer was because they were broken and unnecessary.  You will get all the necessary libraries and RPMs out of the Xen build

**Comment by ts468** [comment]
@andyhhp, thank you so much! I've modified the pq according to your suggestions. The corresponding PR is linked above.
However, I'm still running into an error: https://gist.github.com/ts468/8bca1532b936f03d77d8 . Could you maybe have another look at it?

Removing the ocaml-xen-lowlevel-libs helped! Apparently, I wasn't building all necessary tools with Xen before so that something was missing without the ocaml-xen-lowlevel-libs. But now that part works :)

**Comment by andyhhp** [comment]
Ah - you need similar set of "#ifndef \__MINIOS\__" blocked for the final two hunks of https://github.com/xenserver/xen-4.5.pg/blob/master/master/0003-HACK-tools-libxc-save-restore-v2-framework.patch but that should have been caught by the upstream patch.

As you can perhaps guess by opening PR1, this isn't actually how our team works.  In our case, github is just a simple mirror.  Aready pending (for when we can next merge to trunk) is the upstream patch and a different varient of the writev which I indent to upstream in due course.  I will see that the rest of the stubdom build functions correctly, but the results wont hit github for a little while.

**Comment by ts468** [comment]
@andyhhp, thank you very much for your help and for the details about how you use github! Xen4.5 + pq now builds fine so that I can continue with integrating the XAPI toolchain in NixOS :).

**Comment by andyhhp** [comment]
The changesets which have just appeared in xenserver/xen-4.5.pg should fix all of your stubdom compile issues

**Comment by ts468** [comment]
Great! Thank you so much!
